In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
#create 1d array
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a,b)
print(type(a))
print(type(b)) #nd>> n-dimensional array

[1 2 3 4 5] [ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
print(a+b)
print(a*b)
print(a-b)


[ 7  9 11 13 15]
[ 6 14 24 36 50]
[-5 -5 -5 -5 -5]


In [17]:
#2d matrix
n2=np.array([[1,2],[2,3],[3,4]])
print(n2)


[[1 2]
 [2 3]
 [3 4]]


In [20]:
n2=np.array([[1,2],[2,3],[4,5]])
print(n2)

[[1 2]
 [2 3]
 [4 5]]


In [18]:
#commands
print(n2.shape) #determines the no. of rows and column
print(n2.ndim) #determinr the dimension basis of rows
print(n2.dtype) #determines the data type of the values in array

(3, 2)
2
int64


In [23]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
np.random.randint(1,10,size=(3,3))

array([[3, 9, 4],
       [3, 3, 3],
       [3, 6, 4]], dtype=int32)

In [30]:
x=np.array([[7,2,3],[2,5,2],[3,5,1]])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(x @ y) # or np.dot(x,y) [printing the mutiplication of matrix]

[[36 48 60]
 [36 45 54]
 [30 39 48]]


In [34]:
x.prod() # product of all the element -of x


np.int64(12600)

In [35]:
x.mean()

np.float64(3.3333333333333335)

In [38]:
x.mean(axis=0) #mean of the column wise
x.mean(axis=1) #mean row wise


array([4., 4., 2.])

In [45]:
print(x.min(axis=0)) # column wise mininmum
print(y.min(axis=1)) #row wise minimum

[1 2 5]
[1 4 7]


In [46]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [6]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50)) #median : 50==>50% of the data
print(np.percentile(a,25)) #1st quartile 
print(np.percentile(a,75)) #3rd quartile 

NameError: name 'np' is not defined

In [50]:
print(np.unique(x))

[1 2 3 5 7]


In [7]:
#reshaping of Array
c=np.random.randint(11,101,(4,4))
print(c)
print(c.reshape(2,5))

NameError: name 'np' is not defined